SET FOREIGN_KEY_CHECKS = 0;


-- =====================================================================
--  1. review — 50건
-- =====================================================================
INSERT INTO `review` (`id`, `content`, `created_at`, `deleted_at`, `lecture_id`, `rating`, `status`, `user_id`)
VALUES
    (1, '집에서 바로 해먹을 수 있는 메뉴라 실용적이었어요.', NOW() - INTERVAL 28 DAY, NULL, 2, 5, 'ACTIVE', 79),
    (2, '집에서 바로 해먹을 수 있는 메뉴라 실용적이었어요.', NOW() - INTERVAL 26 DAY, NULL, 19, 5, 'ACTIVE', 80),
    (3, '기초부터 차근차근 배울 수 있어서 만족스러웠어요.', NOW() - INTERVAL 26 DAY, NULL, 35, 2, 'ACTIVE', 60),
    (4, '운동 자세 교정에 정말 도움 많이 됐습니다. 추천해요!', NOW() - INTERVAL 21 DAY, NULL, 1, 4, 'ACTIVE', 73),
    (5, '집에서 바로 해먹을 수 있는 메뉴라 실용적이었어요.', NOW() - INTERVAL 19 DAY, NULL, 22, 5, 'ACTIVE', 72),
    (6, '제 피부 타입에 맞는 팁을 알 수 있어서 좋았어요.', NOW() - INTERVAL 19 DAY, NULL, 36, 3, 'ACTIVE', 95),
    (7, '개념 설명이 명확해서 이해하는 데 큰 도움이 됐어요.', NOW() - INTERVAL 14 DAY, NULL, 3, 2, 'ACTIVE', 73),
    (8, '동작 하나하나 이유를 설명해주셔서 이해하기 좋았습니다.', NOW() - INTERVAL 13 DAY, NULL, 41, 2, 'ACTIVE', 121),
    (9, '운동 자세 교정에 정말 도움 많이 됐습니다. 추천해요!', NOW() - INTERVAL 12 DAY, NULL, 21, 4, 'ACTIVE', 79),
    (10, '제 피부 타입에 맞는 팁을 알 수 있어서 좋았어요.', NOW() - INTERVAL 12 DAY, NULL, 6, 5, 'ACTIVE', 66),
    (11, '그림 그리는 재미를 새롭게 느끼게 해준 강의였어요.', NOW() - INTERVAL 11 DAY, NULL, 7, 4, 'ACTIVE', 121),
    (12, '재료 손질부터 자세히 알려주셔서 정말 유용했어요.', NOW() - INTERVAL 11 DAY, NULL, 29, 5, 'ACTIVE', 86),
    (13, '실습 과정을 자세히 보여주셔서 이해가 잘 됐습니다.', NOW() - INTERVAL 10 DAY, NULL, 38, 4, 'ACTIVE', 93),
    (14, '설명이 친절해서 요리에 자신감이 생겼습니다.', NOW() - INTERVAL 10 DAY, NULL, 39, 3, 'ACTIVE', 23),
    (15, '설명이 꼼꼼해서 초보자도 부담 없이 들을 수 있었어요.', NOW() - INTERVAL 9 DAY, NULL, 11, 3, 'ACTIVE', 61),
    (16, '실습 위주라 지루하지 않고 재밌게 들었습니다.', NOW() - INTERVAL 8 DAY, NULL, 43, 5, 'ACTIVE', 66),
    (17, '제 피부 타입에 맞는 팁을 알 수 있어서 좋았어요.', NOW() - INTERVAL 8 DAY, NULL, 5, 4, 'ACTIVE', 24),
    (18, '완성작을 보니 뿌듯하네요, 좋은 강의였습니다.', NOW() - INTERVAL 7 DAY, NULL, 37, 5, 'ACTIVE', 90),
    (19, '차근차근 짚어주셔서 기초를 탄탄히 다질 수 있었어요.', NOW() - INTERVAL 7 DAY, NULL, 40, 1, 'ACTIVE', 23),
    (20, '레시피가 간단한데 맛은 확실히 살아있어서 놀랐어요.', NOW() - INTERVAL 7 DAY, NULL, 9, 5, 'ACTIVE', 37),
    (21, '기초 기법부터 차근차근 알려주셔서 좋았습니다.', NOW() - INTERVAL 7 DAY, NULL, 17, 4, 'ACTIVE', 74),
    (22, '재료 손질부터 자세히 알려주셔서 정말 유용했어요.', NOW() - INTERVAL 7 DAY, NULL, 32, 4, 'ACTIVE', 70),
    (23, '개념 설명이 명확해서 이해하는 데 큰 도움이 됐어요.', NOW() - INTERVAL 6 DAY, NULL, 33, 5, 'ACTIVE', 38),
    (24, '그림 그리는 재미를 새롭게 느끼게 해준 강의였어요.', NOW() - INTERVAL 6 DAY, NULL, 48, 5, 'ACTIVE', 57),
    (25, '실습 과정을 자세히 보여주셔서 이해가 잘 됐습니다.', NOW() - INTERVAL 6 DAY, NULL, 27, 4, 'ACTIVE', 43),
    (26, '개념 설명이 명확해서 이해하는 데 큰 도움이 됐어요.', NOW() - INTERVAL 5 DAY, NULL, 30, 3, 'ACTIVE', 74),
    (27, '매일 조금씩 따라했더니 확실히 몸이 가벼워진 느낌이에요.', NOW() - INTERVAL 5 DAY, NULL, 24, 5, 'ACTIVE', 105),
    (28, '레시피가 간단한데 맛은 확실히 살아있어서 놀랐어요.', NOW() - INTERVAL 4 DAY, NULL, 32, 4, 'ACTIVE', 40),
    (29, '궁금했던 부분을 정확히 짚어주셔서 만족스러웠어요.', NOW() - INTERVAL 4 DAY, NULL, 20, 5, 'ACTIVE', 31),
    (30, '설명이 친절해서 요리에 자신감이 생겼습니다.', NOW() - INTERVAL 4 DAY, NULL, 42, 4, 'ACTIVE', 120),
    (31, '손이 서툴러도 따라가기 쉽게 설명해주셨어요.', NOW() - INTERVAL 4 DAY, NULL, 8, 4, 'ACTIVE', 117),
    (32, '개념 설명이 명확해서 이해하는 데 큰 도움이 됐어요.', NOW() - INTERVAL 3 DAY, NULL, 13, 4, 'ACTIVE', 73),
    (33, '차근차근 짚어주셔서 기초를 탄탄히 다질 수 있었어요.', NOW() - INTERVAL 3 DAY, NULL, 50, 5, 'ACTIVE', 93),
    (34, '실습 위주라 지루하지 않고 재밌게 들었습니다.', NOW() - INTERVAL 3 DAY, NULL, 23, 5, 'ACTIVE', 89),
    (35, '매일 조금씩 따라했더니 확실히 몸이 가벼워진 느낌이에요.', NOW() - INTERVAL 3 DAY, NULL, 14, 5, 'ACTIVE', 101),
    (36, '실제로 적용해보니 확실히 효과가 느껴졌습니다.', NOW() - INTERVAL 2 DAY, NULL, 45, 3, 'ACTIVE', 65),
    (37, '매일 조금씩 따라했더니 확실히 몸이 가벼워진 느낌이에요.', NOW() - INTERVAL 2 DAY, NULL, 4, 4, 'ACTIVE', 40),
    (38, '요리 초보인데도 실패 없이 따라할 수 있었습니다.', NOW() - INTERVAL 2 DAY, NULL, 12, 4, 'ACTIVE', 120),
    (39, '기초부터 차근차근 배울 수 있어서 만족스러웠어요.', NOW() - INTERVAL 1 DAY, NULL, 46, 5, 'ACTIVE', 81),
    (40, '설명이 자세해서 처음 시도하는 데 부담이 없었어요.', NOW() - INTERVAL 1 DAY, NULL, 16, 4, 'ACTIVE', 121),
    (41, '따라하기 쉬운 순서로 설명해주셔서 도움이 많이 됐습니다.', NOW() - INTERVAL 1 DAY, NULL, 25, 4, 'ACTIVE', 95),
    (42, '기초 기법부터 차근차근 알려주셔서 좋았습니다.', NOW() - INTERVAL 1 DAY, NULL, 47, 5, 'ACTIVE', 102),
    (43, '동작 하나하나 이유를 설명해주셔서 이해하기 좋았습니다.', NOW() - INTERVAL 1 DAY, NULL, 44, 2, 'ACTIVE', 93),
    (44, '설명이 자세해서 처음 시도하는 데 부담이 없었어요.', NOW() - INTERVAL 1 DAY, NULL, 26, 4, 'ACTIVE', 56),
    (45, '기초 기법부터 차근차근 알려주셔서 좋았습니다.', NOW() - INTERVAL 1 DAY, NULL, 28, 1, 'ACTIVE', 29),
    (46, '설명이 자세해서 처음 시도하는 데 부담이 없었어요.', NOW() - INTERVAL 1 DAY, NULL, 15, 4, 'ACTIVE', 29),
    (47, '동작 하나하나 이유를 설명해주셔서 이해하기 좋았습니다.', NOW() - INTERVAL 1 DAY, NULL, 34, 4, 'ACTIVE', 105),
    (48, '요리 초보인데도 실패 없이 따라할 수 있었습니다.', NOW() - INTERVAL 1 DAY, NULL, 49, 4, 'ACTIVE', 20),
    (49, '매일 조금씩 따라했더니 확실히 몸이 가벼워진 느낌이에요.', NOW() - INTERVAL 1 DAY, NULL, 31, 5, 'ACTIVE', 56),
    (50, '실습 위주라 지루하지 않고 재밌게 들었습니다.', NOW() - INTERVAL 1 DAY, NULL, 10, 2, 'ACTIVE', 23)
    ON DUPLICATE KEY UPDATE
                         content = VALUES(content),
                         created_at = VALUES(created_at),
                         deleted_at = VALUES(deleted_at),
                         lecture_id = VALUES(lecture_id),
                         rating = VALUES(rating),
                         status = VALUES(status),
                         user_id = VALUES(user_id);
-- =====================================================================
--  2. building — 65건
-- =====================================================================
INSERT INTO `building` (`id`, `created_at`, `updated_at`, `category`, `level`, `position`, `user_id`)
VALUES
    (1, NOW() - INTERVAL 30 DAY, NOW() - INTERVAL 30 DAY, 'FITNESS', 2, 1, 73),
    (2, NOW() - INTERVAL 17 DAY, NOW() - INTERVAL 17 DAY, 'BEAUTY', 1, 2, 21),
    (3, NOW() - INTERVAL 15 DAY, NOW() - INTERVAL 15 DAY, 'FITNESS', 1, 3, 21),
    (4, NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 14 DAY, 'COOK', 1, 4, 72),
    (5, NOW() - INTERVAL 13 DAY, NOW() - INTERVAL 13 DAY, 'STUDY', 1, 5, 71),
    (6, NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 12 DAY, 'STUDY', 2, 2, 73),
    (7, NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 12 DAY, 'COOK', 2, 2, 102),
    (8, NOW() - INTERVAL 11 DAY, NOW() - INTERVAL 11 DAY, 'COOK', 2, 3, 80),
    (9, NOW() - INTERVAL 8 DAY, NOW() - INTERVAL 8 DAY, 'STUDY', 2, 4, 60),
    (10, NOW() - INTERVAL 7 DAY, NOW() - INTERVAL 7 DAY, 'COOK', 2, 5, 120),
    (11, NOW() - INTERVAL 7 DAY, NOW() - INTERVAL 7 DAY, 'STUDY', 1, 1, 49),
    (12, NOW() - INTERVAL 6 DAY, NOW() - INTERVAL 6 DAY, 'BEAUTY', 1, 2, 121),
    (13, NOW() - INTERVAL 6 DAY, NOW() - INTERVAL 6 DAY, 'FITNESS', 1, 3, 64),
    (14, NOW() - INTERVAL 5 DAY, NOW() - INTERVAL 5 DAY, 'BEAUTY', 2, 4, 65),
    (15, NOW() - INTERVAL 4 DAY, NOW() - INTERVAL 4 DAY, 'COOK', 2, 5, 42),
    (16, NOW() - INTERVAL 4 DAY, NOW() - INTERVAL 4 DAY, 'STUDY', 2, 1, 32),
    (17, NOW() - INTERVAL 4 DAY, NOW() - INTERVAL 4 DAY, 'ART', 2, 2, 100),
    (18, NOW() - INTERVAL 4 DAY, NOW() - INTERVAL 4 DAY, 'BEAUTY', 1, 3, 100),
    (19, NOW() - INTERVAL 3 DAY, NOW() - INTERVAL 3 DAY, 'BEAUTY', 3, 4, 81),
    (20, NOW() - INTERVAL 3 DAY, NOW() - INTERVAL 3 DAY, 'BEAUTY', 3, 5, 38),
    (21, NOW() - INTERVAL 3 DAY, NOW() - INTERVAL 3 DAY, 'COOK', 2, 1, 70),
    (22, NOW() - INTERVAL 3 DAY, NOW() - INTERVAL 3 DAY, 'BEAUTY', 2, 2, 29),
    (23, NOW() - INTERVAL 3 DAY, NOW() - INTERVAL 3 DAY, 'STUDY', 2, 3, 31),
    (24, NOW() - INTERVAL 3 DAY, NOW() - INTERVAL 3 DAY, 'STUDY', 1, 4, 66),
    (25, NOW() - INTERVAL 2 DAY, NOW() - INTERVAL 2 DAY, 'BEAUTY', 3, 5, 50),
    (26, NOW() - INTERVAL 2 DAY, NOW() - INTERVAL 2 DAY, 'FITNESS', 2, 1, 55),
    (27, NOW() - INTERVAL 2 DAY, NOW() - INTERVAL 2 DAY, 'FITNESS', 2, 2, 65),
    (28, NOW() - INTERVAL 2 DAY, NOW() - INTERVAL 2 DAY, 'BEAUTY', 2, 3, 42),
    (29, NOW() - INTERVAL 2 DAY, NOW() - INTERVAL 2 DAY, 'COOK', 2, 4, 56),
    (30, NOW() - INTERVAL 2 DAY, NOW() - INTERVAL 2 DAY, 'FITNESS', 2, 5, 61),
    (31, NOW() - INTERVAL 2 DAY, NOW() - INTERVAL 2 DAY, 'STUDY', 2, 1, 74),
    (32, NOW() - INTERVAL 2 DAY, NOW() - INTERVAL 2 DAY, 'ART', 1, 2, 39),
    (33, NOW() - INTERVAL 2 DAY, NOW() - INTERVAL 2 DAY, 'FITNESS', 1, 3, 119),
    (34, NOW() - INTERVAL 1 DAY, NOW() - INTERVAL 1 DAY, 'STUDY', 3, 4, 23),
    (35, NOW() - INTERVAL 1 DAY, NOW() - INTERVAL 1 DAY, 'COOK', 3, 5, 79),
    (36, NOW() - INTERVAL 1 DAY, NOW() - INTERVAL 1 DAY, 'BEAUTY', 3, 1, 95),
    (37, NOW() - INTERVAL 1 DAY, NOW() - INTERVAL 1 DAY, 'ART', 2, 2, 117),
    (38, NOW() - INTERVAL 1 DAY, NOW() - INTERVAL 1 DAY, 'FITNESS', 2, 3, 105),
    (39, NOW() - INTERVAL 1 DAY, NOW() - INTERVAL 1 DAY, 'BEAUTY', 2, 2, 56),
    (40, NOW() - INTERVAL 1 DAY, NOW() - INTERVAL 1 DAY, 'COOK', 2, 5, 24),
    (41, NOW() - INTERVAL 1 DAY, NOW() - INTERVAL 1 DAY, 'COOK', 2, 1, 75),
    (42, NOW() - INTERVAL 1 DAY, NOW() - INTERVAL 1 DAY, 'STUDY', 2, 2, 57),
    (43, NOW() - INTERVAL 1 DAY, NOW() - INTERVAL 1 DAY, 'BEAUTY', 2, 3, 60),
    (44, NOW() - INTERVAL 1 DAY, NOW() - INTERVAL 1 DAY, 'FITNESS', 2, 4, 93),
    (45, NOW() - INTERVAL 1 DAY, NOW() - INTERVAL 1 DAY, 'ART', 2, 5, 102),
    (46, NOW() - INTERVAL 1 DAY, NOW() - INTERVAL 1 DAY, 'COOK', 2, 1, 37),
    (47, NOW() - INTERVAL 1 DAY, NOW() - INTERVAL 1 DAY, 'FITNESS', 1, 2, 79),
    (48, NOW() - INTERVAL 1 DAY, NOW() - INTERVAL 1 DAY, 'STUDY', 1, 3, 70),
    (49, NOW() - INTERVAL 1 DAY, NOW() - INTERVAL 1 DAY, 'STUDY', 1, 4, 90),
    (50, NOW() - INTERVAL 1 DAY, NOW() - INTERVAL 1 DAY, 'COOK', 1, 2, 61)
    ON DUPLICATE KEY UPDATE
                         created_at = VALUES(created_at),
                         updated_at = VALUES(updated_at),
                         category = VALUES(category),
                         level = VALUES(level),
                         position = VALUES(position),
                         user_id = VALUES(user_id);

INSERT INTO `building` (`id`, `created_at`, `updated_at`, `category`, `level`, `position`, `user_id`)
VALUES
    (4, NOW() - INTERVAL 23 DAY, NOW() - INTERVAL 23 DAY, 'COOK', 1, 1, 72),
    (11, NOW() - INTERVAL 10 DAY, NOW() - INTERVAL 10 DAY, 'STUDY', 1, 2, 49),
    (14, NOW() - INTERVAL 15 DAY, NOW() - INTERVAL 15 DAY, 'BEAUTY', 2, 4, 65),
    (15, NOW() - INTERVAL 25 DAY, NOW() - INTERVAL 25 DAY, 'COOK', 2, 2, 42),
    (16, NOW() - INTERVAL 33 DAY, NOW() - INTERVAL 33 DAY, 'STUDY', 2, 1, 32),
    (22, NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 14 DAY, 'BEAUTY', 2, 4, 29),
    (27, NOW() - INTERVAL 6 DAY, NOW() - INTERVAL 6 DAY, 'FITNESS', 2, 1, 65),
    (28, NOW() - INTERVAL 23 DAY, NOW() - INTERVAL 23 DAY, 'BEAUTY', 2, 3, 42),
    (41, NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 14 DAY, 'COOK', 2, 3, 75),
    (44, NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 12 DAY, 'FITNESS', 2, 1, 93),
    (46, NOW() - INTERVAL 8 DAY, NOW() - INTERVAL 8 DAY, 'COOK', 2, 2, 37),
    (49, NOW() - INTERVAL 7 DAY, NOW() - INTERVAL 7 DAY, 'STUDY', 1, 1, 90),
    (65, NOW() - INTERVAL 21 DAY, NOW() - INTERVAL 21 DAY, 'ART', 1, 1, 18),
    (66, NOW() - INTERVAL 8 DAY, NOW() - INTERVAL 8 DAY, 'FITNESS', 1, 1, 19),
    (67, NOW() - INTERVAL 18 DAY, NOW() - INTERVAL 18 DAY, 'STUDY', 1, 2, 19),
    (68, NOW() - INTERVAL 7 DAY, NOW() - INTERVAL 7 DAY, 'ART', 1, 3, 19),
    (76, NOW() - INTERVAL 16 DAY, NOW() - INTERVAL 16 DAY, 'FITNESS', 1, 1, 29),
    (77, NOW() - INTERVAL 18 DAY, NOW() - INTERVAL 18 DAY, 'STUDY', 1, 2, 29),
    (78, NOW() - INTERVAL 9 DAY, NOW() - INTERVAL 9 DAY, 'COOK', 1, 3, 29),
    (79, NOW() - INTERVAL 1 DAY, NOW() - INTERVAL 1 DAY, 'ART', 1, 5, 29),
    (83, NOW() - INTERVAL 6 DAY, NOW() - INTERVAL 6 DAY, 'BEAUTY', 1, 1, 33),
    (84, NOW() - INTERVAL 20 DAY, NOW() - INTERVAL 20 DAY, 'STUDY', 1, 1, 36),
    (85, NOW() - INTERVAL 23 DAY, NOW() - INTERVAL 23 DAY, 'BEAUTY', 1, 2, 36),
    (86, NOW() - INTERVAL 4 DAY, NOW() - INTERVAL 4 DAY, 'FITNESS', 1, 1, 37),
    (94, NOW() - INTERVAL 1 DAY, NOW() - INTERVAL 1 DAY, 'STUDY', 1, 1, 42),
    (95, NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 14 DAY, 'ART', 1, 4, 42),
    (104, NOW() - INTERVAL 7 DAY, NOW() - INTERVAL 7 DAY, 'FITNESS', 1, 1, 49),
    (109, NOW() - INTERVAL 19 DAY, NOW() - INTERVAL 19 DAY, 'STUDY', 1, 1, 51),
    (110, NOW() - INTERVAL 15 DAY, NOW() - INTERVAL 15 DAY, 'COOK', 1, 2, 51),
    (113, NOW() - INTERVAL 8 DAY, NOW() - INTERVAL 8 DAY, 'FITNESS', 1, 1, 53),
    (114, NOW() - INTERVAL 5 DAY, NOW() - INTERVAL 5 DAY, 'STUDY', 1, 2, 53),
    (115, NOW() - INTERVAL 27 DAY, NOW() - INTERVAL 27 DAY, 'ART', 1, 3, 53),
    (116, NOW() - INTERVAL 22 DAY, NOW() - INTERVAL 22 DAY, 'ART', 1, 1, 54),
    (130, NOW() - INTERVAL 9 DAY, NOW() - INTERVAL 9 DAY, 'STUDY', 1, 1, 63),
    (131, NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 14 DAY, 'ART', 1, 2, 63),
    (135, NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 14 DAY, 'STUDY', 1, 2, 65),
    (136, NOW() - INTERVAL 51 DAY, NOW() - INTERVAL 51 DAY, 'COOK', 1, 3, 65),
    (137, NOW() - INTERVAL 22 DAY, NOW() - INTERVAL 22 DAY, 'ART', 1, 5, 65),
    (143, NOW() - INTERVAL 4 DAY, NOW() - INTERVAL 4 DAY, 'FITNESS', 1, 1, 69),
    (144, NOW() - INTERVAL 4 DAY, NOW() - INTERVAL 4 DAY, 'COOK', 1, 2, 69),
    (149, NOW() - INTERVAL 7 DAY, NOW() - INTERVAL 7 DAY, 'FITNESS', 1, 1, 75),
    (150, NOW() - INTERVAL 10 DAY, NOW() - INTERVAL 10 DAY, 'STUDY', 1, 2, 75),
    (151, NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 14 DAY, 'ART', 1, 4, 75),
    (153, NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 14 DAY, 'COOK', 1, 1, 77),
    (154, NOW() - INTERVAL 29 DAY, NOW() - INTERVAL 29 DAY, 'ART', 1, 2, 77),
    (155, NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 12 DAY, 'FITNESS', 1, 1, 78),
    (161, NOW() - INTERVAL 33 DAY, NOW() - INTERVAL 33 DAY, 'BEAUTY', 1, 1, 83),
    (165, NOW() - INTERVAL 19 DAY, NOW() - INTERVAL 19 DAY, 'COOK', 1, 1, 86),
    (166, NOW() - INTERVAL 13 DAY, NOW() - INTERVAL 13 DAY, 'ART', 1, 2, 86),
    (169, NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 12 DAY, 'FITNESS', 1, 1, 88),
    (170, NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 12 DAY, 'COOK', 1, 2, 88),
    (174, NOW() - INTERVAL 6 DAY, NOW() - INTERVAL 6 DAY, 'BEAUTY', 1, 2, 90),
    (175, NOW() - INTERVAL 28 DAY, NOW() - INTERVAL 28 DAY, 'ART', 1, 3, 90),
    (181, NOW() - INTERVAL 20 DAY, NOW() - INTERVAL 20 DAY, 'STUDY', 1, 2, 93),
    (182, NOW() - INTERVAL 1 DAY, NOW() - INTERVAL 1 DAY, 'COOK', 1, 3, 93),
    (187, NOW() - INTERVAL 7 DAY, NOW() - INTERVAL 7 DAY, 'COOK', 1, 1, 96),
    (188, NOW() - INTERVAL 3 DAY, NOW() - INTERVAL 3 DAY, 'ART', 1, 2, 96),
    (189, NOW() - INTERVAL 3 DAY, NOW() - INTERVAL 3 DAY, 'COOK', 1, 1, 97),
    (190, NOW() - INTERVAL 8 DAY, NOW() - INTERVAL 8 DAY, 'BEAUTY', 1, 1, 99),
    (191, NOW() - INTERVAL 18 DAY, NOW() - INTERVAL 18 DAY, 'ART', 1, 2, 99),
    (204, NOW() - INTERVAL 28 DAY, NOW() - INTERVAL 28 DAY, 'ART', 1, 1, 118),
    (215, NOW() - INTERVAL 23 DAY, NOW() - INTERVAL 23 DAY, 'FITNESS', 1, 1, 122),
    (216, NOW() - INTERVAL 8 DAY, NOW() - INTERVAL 8 DAY, 'ART', 1, 2, 122),
    (219, NOW() - INTERVAL 8 DAY, NOW() - INTERVAL 8 DAY, 'FITNESS', 1, 1, 124),
    (220, NOW() - INTERVAL 17 DAY, NOW() - INTERVAL 17 DAY, 'ART', 1, 2, 124)
    ON DUPLICATE KEY UPDATE
                         created_at = VALUES(created_at),
                         updated_at = VALUES(updated_at),
                         category = VALUES(category),
                         level = VALUES(level),
                         position = VALUES(position),
                         user_id = VALUES(user_id);

-- 민수 건물 추가
INSERT INTO `building` (`id`, `created_at`, `updated_at`, `category`, `level`, `position`, `user_id`)
VALUES
    (226, NOW() - INTERVAL 5 DAY, NOW() - INTERVAL 5 DAY, 'BEAUTY', 1, 1, 12),
    (227, NOW() - INTERVAL 1 DAY, NOW() - INTERVAL 1 DAY, 'COOK', 1, 2, 12)
    ON DUPLICATE KEY UPDATE
                         created_at = VALUES(created_at),
                         updated_at = VALUES(updated_at),
                         category = VALUES(category),
                         level = VALUES(level),
                         position = VALUES(position),
                         user_id = VALUES(user_id);

SET FOREIGN_KEY_CHECKS = 1;
