include:
  - src/main/resources/docker-compose.yml

services:
  # MySQL 설정
  mysql:
    image: mysql:8.0
    container_name: momo-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: legend_momocity
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1234" ]
      interval: 10s
      timeout: 5s
      retries: 10
  # Loki 설정
  loki:
    image: grafana/loki:latest
    container_name: momo-loki
    ports:
      - "3100:3100"
  # Promtail 설정
  promtail:
    image: grafana/promtail:latest
    container_name: momo-promtail
    ports:
      - "9080:9080"
    volumes:
      - ./docker/promtail/promtail-config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
  # Grafana 설정
  grafana:
    image: grafana/grafana:latest
    container_name: momo-grafana
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - loki
  # Prometheus 설정
  prometheus:
    image: prom/prometheus:latest
    container_name: momo-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mysql_data:
  grafana_data:
  prometheus_data:



