name: 🐞 Bug Report
description: 버그 리포트 (BE)
title: "[BUG] "
labels: ["bug", "backend"]
body:
  - type: markdown
    attributes:
      value: |
        ## 발견한 버그를 리포트해주세요
        재현 가능한 정보를 최대한 자세히 작성해주시면 빠르게 해결할 수 있습니다.
        버그 해결 하기 전에 미리 작성해주세요

  - type: textarea
    id: description
    attributes:
      label: 버그 설명
    validations:
      required: true

  - type: dropdown
    id: env
    attributes:
      label: 환경
      options:
        - Local
        - Dev
        - Staging
        - Production
    validations:
      required: true