# 위치: docker/prometheus/prometheus.yml

global:
  scrape_interval: 15s        # 15초마다 한 번씩 긁는다

scrape_configs:
  - job_name: 'legend-momo-city'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '43.203.214.25:8080' ]   # BE 서버 퍼블릭 IP
      # 앱이 같은 컴포즈 네트워크 안으로 들어와서 서비스명으로 스크랩 (2026-07-01)
#      - targets: ['app:8080']