USE `momo`;
SET FOREIGN_KEY_CHECKS = 0;

-- =====================================================================
--  1. user — 30명
-- =====================================================================
INSERT INTO `user` (`id`, `email`, `password`, `name`, `nickname`, `profile_image_url`, `role`, `status`, `category`, `proof`, `point`, `do_not_disturb`, `membership`, `membership_start`, `suspension_count`, `suspended_until`, `created_at`, `updated_at`, `deleted_at`, `is_tempPWD`) VALUES
  (1, 'admin@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '관리자', '모모관리자', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/momoProfile.png', 'ADMIN', 'ACTIVE', NULL, NULL, 0, 0, 'PRO', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 147 DAY, NOW() - INTERVAL 147 DAY, NULL, 0),
  (2, 'teacher_fit1@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '김강사', '호랑이쌤', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/FITNESSProfile.png', 'TEACHER', 'ACTIVE', 'FITNESS', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/proof/teacher_fit1.pdf', 0, 0, 'BASIC', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 129 DAY, NOW() - INTERVAL 129 DAY, NULL, 0),
  (3, 'teacher_fit2@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '이필라', '필라쌤', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/FITNESSProfile.png', 'TEACHER', 'ACTIVE', 'FITNESS', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/proof/teacher_fit2.pdf', 0, 0, 'BASIC', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 110 DAY, NOW() - INTERVAL 129 DAY, NULL, 0),
  (4, 'teacher_cook1@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '박백종', '요리왕', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/COOKProfile.png', 'TEACHER', 'ACTIVE', 'COOK', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/proof/teacher_cook1.pdf', 0, 0, 'BASIC', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 124 DAY, NOW() - INTERVAL 129 DAY, NULL, 0),
  (5, 'teacher_cook2@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '최파티', '파티쉐', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/COOKProfile.png', 'TEACHER', 'ACTIVE', 'COOK', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/proof/teacher_cook2.pdf', 0, 0, 'BASIC', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 100 DAY, NOW() - INTERVAL 129 DAY, NULL, 0),
  (6, 'teacher_study1@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '정교수', '코딩쌤', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/STUDYProfile.png', 'TEACHER', 'ACTIVE', 'STUDY', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/proof/teacher_study1.pdf', 0, 0, 'BASIC', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 120 DAY, NOW() - INTERVAL 129 DAY, NULL, 0),
  (7, 'teacher_study2@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '윤영어', '영어쌤', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/STUDYProfile.png', 'TEACHER', 'ACTIVE', 'STUDY', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/proof/teacher_study2.pdf', 0, 0, 'BASIC', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 95 DAY, NOW() - INTERVAL 129 DAY, NULL, 0),
  (8, 'teacher_beauty@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '한뷰티', '뷰티쌤', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/BEAUTYProfile.png', 'TEACHER', 'ACTIVE', 'BEAUTY', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/proof/teacher_beauty.pdf', 0, 0, 'BASIC', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 88 DAY, NOW() - INTERVAL 129 DAY, NULL, 0),
  (9, 'teacher_art@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '송아티', '아트쌤', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/ARTProfile.png', 'TEACHER', 'ACTIVE', 'ART', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/proof/teacher_art.pdf', 0, 0, 'BASIC', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 80 DAY, NOW() - INTERVAL 129 DAY, NULL, 0),
  (10, 'pending1@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '정대기', '대기자1', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/STUDYProfile.png', 'TEACHER', 'PENDING', 'STUDY', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/proof/pending1.pdf', 0, 0, 'BASIC', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 9 DAY, NOW() - INTERVAL 129 DAY, NULL, 0),
  (11, 'pending2@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '오대기', '대기자2', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/ARTProfile.png', 'TEACHER', 'PENDING', 'ART', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/proof/pending2.pdf', 0, 0, 'BASIC', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 5 DAY, NOW() - INTERVAL 129 DAY, NULL, 0),
  (12, 'student1@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '김민수', '민수', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/store/item01.png', 'STUDENT', 'ACTIVE', NULL, NULL, 0, 1, 'BASIC', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 108 DAY, NOW() - INTERVAL 129 DAY, NULL, 0),
  (13, 'student2@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '이지영', '지영', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/momoProfile.png', 'STUDENT', 'ACTIVE', NULL, NULL, 79, 0, 'PLUS', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 103 DAY, NOW() - INTERVAL 129 DAY, NULL, 0),
  (14, 'student3@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '박현우', '현우', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/momoProfile.png', 'STUDENT', 'ACTIVE', NULL, NULL, 60, 1, 'PRO', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 89 DAY, NOW() - INTERVAL 129 DAY, NULL, 0),
  (15, 'student4@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '최서연', '서연', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/momoProfile.png', 'STUDENT', 'ACTIVE', NULL, NULL, 79, 0, 'PLUS', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 78 DAY, NOW() - INTERVAL 129 DAY, NULL, 0),
  (16, 'student5@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '강도현', '도현', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/momoProfile.png', 'STUDENT', 'ACTIVE', NULL, NULL, 137, 0, 'BASIC', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 70 DAY, NOW() - INTERVAL 129 DAY, NULL, 0),
  (17, 'student6@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '윤하늘', '하늘', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/momoProfile.png', 'STUDENT', 'ACTIVE', NULL, NULL, 0, 1, 'PLUS', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 65 DAY, NOW() - INTERVAL 129 DAY, NULL, 0),
  (18, 'student7@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '임채원', '채원', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/momoProfile.png', 'STUDENT', 'ACTIVE', NULL, NULL, 50, 0, 'PRO', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 55 DAY, NOW() - INTERVAL 129 DAY, NULL, 0),
  (19, 'student8@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '오승준', '승준', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/store/item08.png', 'STUDENT', 'ACTIVE', NULL, NULL, 28, 1, 'PLUS', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 48 DAY, NOW() - INTERVAL 129 DAY, NULL, 0),
  (20, 'student9@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '신유진', '유진', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/momoProfile.png', 'STUDENT', 'ACTIVE', NULL, NULL, 10, 0, 'BASIC', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 40 DAY, NOW() - INTERVAL 129 DAY, NULL, 0),
  (21, 'student10@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '류지훈', '지훈', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/momoProfile.png', 'STUDENT', 'ACTIVE', NULL, NULL, 0, 0, 'BASIC', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 35 DAY, NOW() - INTERVAL 129 DAY, NULL, 0),
  (22, 'student11@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '문소희', '소희', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/momoProfile.png', 'STUDENT', 'ACTIVE', NULL, NULL, 45, 1, 'PRO', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 30 DAY, NOW() - INTERVAL 129 DAY, NULL, 0),
  (23, 'student12@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '배태양', '태양', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/momoProfile.png', 'STUDENT', 'ACTIVE', NULL, NULL, 130, 1, 'BASIC', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 25 DAY, NOW() - INTERVAL 129 DAY, NULL, 0),
  (24, 'rejected1@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '한거절', '거절자1', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/momoProfile.png', 'STUDENT', 'REJECTED', 'ART', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/proof/rejected1.pdf', 0, 0, 'BASIC', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 19 DAY, NOW() - INTERVAL 129 DAY, NULL, 0),
  (25, 'rejected2@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '조반려', '거절자2', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/momoProfile.png', 'STUDENT', 'REJECTED', 'FITNESS', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/proof/rejected2.pdf', 0, 0, 'BASIC', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 129 DAY, NULL, 0),
  (26, 'banned@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '노정지', '정지자', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/momoProfile.png', 'STUDENT', 'BANNED', NULL, NULL, 0, 0, 'BASIC', NOW() - INTERVAL 129 DAY, 2, NOW() + INTERVAL 7 DAY, NOW() - INTERVAL 58 DAY, NOW() - INTERVAL 129 DAY, NULL, 0),
  (27, 'black@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '영구정', '블랙리스트', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/momoProfile.png', 'STUDENT', 'BLACK', NULL, NULL, 0, 0, 'BASIC', NOW() - INTERVAL 129 DAY, 5, NULL, NOW() - INTERVAL 68 DAY, NOW() - INTERVAL 129 DAY, NULL, 0),
  (28, 'left@momo.city', '$2a$10$UbdCvu2c/oz0u9pwp8qD.e1BqOoQdTL1WHicM5odz5OfUChV6lfSm', '떠난이', '탈퇴자', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/momoProfile.png', 'STUDENT', 'DELETED', NULL, NULL, 0, 0, 'BASIC', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 118 DAY, NOW() - INTERVAL 118 DAY, NOW() - INTERVAL 14 DAY, 0),
  (29, NULL, NULL, '카카오유저', '카카오', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/momoProfile.png', 'STUDENT', 'ACTIVE', NULL, NULL, 100, 0, 'BASIC', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 24 DAY, NOW() - INTERVAL 129 DAY, NULL, 0),
  (30, 'google_user_momo@gmail.com', NULL, '구글유저', '구글', 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/profile/momoProfile.png', 'STUDENT', 'ACTIVE', NULL, NULL, 70, 0, 'BASIC', NOW() - INTERVAL 129 DAY, 0, NULL, NOW() - INTERVAL 18 DAY, NOW() - INTERVAL 129 DAY, NULL, 0);
-- =====================================================================
--  2. lecture — 10개 large 실제 데이터
-- =====================================================================
INSERT INTO `lecture` (`id`, `title`, `created_at`, `updated_at`, `deleted_at`, `category`, `completed_user_count`, `description`, `status`, `teacher_id`, `thumbnail_url`) VALUES
  (1, '홈트레이닝 기초', NOW() - INTERVAL 56 DAY, NOW() - INTERVAL 56 DAY, NULL, 'FITNESS', 0, '집에서 할 수 있는 기초 체력 운동을 배웁니다.', 'ACTIVE', 2, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/1/lecture01Thumbnail.png'),
  (2, '집밥 요리 입문', NOW() - INTERVAL 52 DAY, NOW() - INTERVAL 52 DAY, NULL, 'COOK', 0, '초보자도 따라할 수 있는 기본 요리를 배웁니다.', 'ACTIVE', 4, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/2/lecture02Thumbnail.JPG'),
  (3, '프로그래밍 기초', NOW() - INTERVAL 48 DAY, NOW() - INTERVAL 48 DAY, NULL, 'STUDY', 0, '변수, 조건문, 반복문 등 프로그래밍의 기초를 배웁니다.', 'ACTIVE', 6, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/3/lecture03Thumbnail.WEBP'),
  (4, '요가 기초', NOW() - INTERVAL 44 DAY, NOW() - INTERVAL 44 DAY, NULL, 'FITNESS', 0, '몸의 유연성과 균형을 키우는 기초 요가를 배웁니다.', 'ACTIVE', 3, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/4/lecture04Thumbnail.jpeg'),
  (5, '스킨케어 루틴', NOW() - INTERVAL 40 DAY, NOW() - INTERVAL 40 DAY, NULL, 'BEAUTY', 0, '피부 타입별 기초 스킨케어 방법을 배웁니다.', 'ACTIVE', 8, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/5/lecture05Thumbnail.jpeg'),
  (6, '메이크업 기초', NOW() - INTERVAL 36 DAY, NOW() - INTERVAL 36 DAY, NULL, 'BEAUTY', 0, '데일리 메이크업부터 포인트 메이크업까지 기초를 배웁니다.', 'ACTIVE', 8, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/6/lecture06Thumbnail.jpeg'),
  (7, '수채화 입문', NOW() - INTERVAL 32 DAY, NOW() - INTERVAL 32 DAY, NULL, 'ART', 0, '색감과 번짐 기법을 활용한 수채화 기초를 배웁니다.', 'ACTIVE', 9, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/7/lecture07Thumbnail.jpeg'),
  (8, '드로잉 기초', NOW() - INTERVAL 28 DAY, NOW() - INTERVAL 28 DAY, NULL, 'ART', 0, '선 긋기부터 인체 드로잉까지 기초 드로잉을 배웁니다.', 'ACTIVE', 9, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/8/lecture08Thumbnail.jpeg'),
  (9, '베이킹 기초', NOW() - INTERVAL 24 DAY, NOW() - INTERVAL 24 DAY, NULL, 'COOK', 0, '쿠키, 케이크 등 홈베이킹의 기초를 배웁니다.', 'ACTIVE', 5, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/9/lecture09Thumbnail.jpeg'),
  (10, '영어 회화 기초', NOW() - INTERVAL 20 DAY, NOW() - INTERVAL 20 DAY, NULL, 'STUDY', 0, '일상에서 바로 쓸 수 있는 영어 회화 표현을 배웁니다.', 'ACTIVE', 7, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/10/lecture10Thumbnail.jpeg');
-- =====================================================================
--  3. chapter — lecture 1~10 소속
-- =====================================================================
INSERT INTO `chapter` (`id`, `created_at`, `updated_at`, `deleted_at`, `thumbnail_url`, `duration_sec`, `lecture_id`, `order_no`, `original_filename`, `title`, `video_size_bytes`, `video_url`) VALUES
  (1, NOW() - INTERVAL 56 DAY, NOW() - INTERVAL 56 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/1/chapters/1/chapter01Thumbnail.jpg', 1445, 1, 1, NULL, '스트레칭 기초', NULL, 'lectures/1/chapters/1/chapter01.mp4'),
  (2, NOW() - INTERVAL 56 DAY, NOW() - INTERVAL 56 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/1/chapters/2/chapter02Thumbnail.jpg', 200, 1, 2, NULL, '상체 운동 루틴', NULL, 'lectures/1/chapters/2/chapter02.mp4'),
  (3, NOW() - INTERVAL 56 DAY, NOW() - INTERVAL 56 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/1/chapters/3/chapter03Thumbnail.jpg', 805, 1, 3, NULL, '하체 운동 루틴', NULL, 'lectures/1/chapters/3/chapter03.mp4'),
  (4, NOW() - INTERVAL 56 DAY, NOW() - INTERVAL 56 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/1/chapters/4/chapter04Thumbnail.jpg', 217, 1, 4, NULL, '코어 운동 루틴', NULL, 'lectures/1/chapters/4/chapter04.mp4'),
  (5, NOW() - INTERVAL 52 DAY, NOW() - INTERVAL 52 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/2/chapters/1/chapter05Thumbnail.jpg', 1445, 2, 1, NULL, '기본 칼질 익히기', NULL, 'lectures/2/chapters/1/chapter01.mp4'),
  (6, NOW() - INTERVAL 52 DAY, NOW() - INTERVAL 52 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/2/chapters/2/chapter06Thumbnail.jpg', 200, 2, 2, NULL, '국 끓이기', NULL, 'lectures/2/chapters/2/chapter02.mp4'),
  (7, NOW() - INTERVAL 52 DAY, NOW() - INTERVAL 52 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/2/chapters/3/chapter07Thumbnail.jpg', 805, 2, 3, NULL, '볶음 요리 기초', NULL, 'lectures/2/chapters/3/chapter03.mp4'),
  (8, NOW() - INTERVAL 52 DAY, NOW() - INTERVAL 52 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/2/chapters/4/chapter08Thumbnail.jpg', 217, 2, 4, NULL, '찌개 요리 기초', NULL, 'lectures/2/chapters/4/chapter04.mp4'),
  (9, NOW() - INTERVAL 52 DAY, NOW() - INTERVAL 52 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/2/chapters/5/chapter09Thumbnail.jpg', 199, 2, 5, NULL, '디저트 만들기', NULL, 'lectures/2/chapters/5/chapter05.mp4'),
  (10, NOW() - INTERVAL 48 DAY, NOW() - INTERVAL 48 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/3/chapters/1/chapter10Thumbnail.jpg', 1445, 3, 1, NULL, '변수와 타입', NULL, 'lectures/3/chapters/1/chapter01.mp4'),
  (11, NOW() - INTERVAL 48 DAY, NOW() - INTERVAL 48 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/3/chapters/2/chapter11Thumbnail.jpg', 200, 3, 2, NULL, '조건문과 반복문', NULL, 'lectures/3/chapters/2/chapter02.mp4'),
  (12, NOW() - INTERVAL 44 DAY, NOW() - INTERVAL 44 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/4/chapters/1/chapter12Thumbnail.jpg', 1445, 4, 1, NULL, '요가 기본 자세', NULL, 'lectures/4/chapters/1/chapter01.mp4'),
  (13, NOW() - INTERVAL 40 DAY, NOW() - INTERVAL 40 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/5/chapters/1/chapter13Thumbnail.jpg', 1445, 5, 1, NULL, '세안과 보습 기초', NULL, 'lectures/5/chapters/1/chapter01.mp4'),
  (14, NOW() - INTERVAL 40 DAY, NOW() - INTERVAL 40 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/5/chapters/2/chapter14Thumbnail.jpg', 200, 5, 2, NULL, '피부 타입별 케어', NULL, 'lectures/5/chapters/2/chapter02.mp4'),
  (15, NOW() - INTERVAL 40 DAY, NOW() - INTERVAL 40 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/5/chapters/3/chapter15Thumbnail.jpg', 805, 5, 3, NULL, '선크림과 자외선 차단', NULL, 'lectures/5/chapters/3/chapter03.mp4'),
  (16, NOW() - INTERVAL 36 DAY, NOW() - INTERVAL 36 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/6/chapters/1/chapter16Thumbnail.jpg', 1445, 6, 1, NULL, '베이스 메이크업 기초', NULL, 'lectures/6/chapters/1/chapter01.mp4'),
  (17, NOW() - INTERVAL 36 DAY, NOW() - INTERVAL 36 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/6/chapters/2/chapter17Thumbnail.jpg', 200, 6, 2, NULL, '아이브로우 그리기', NULL, 'lectures/6/chapters/2/chapter02.mp4'),
  (18, NOW() - INTERVAL 36 DAY, NOW() - INTERVAL 36 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/6/chapters/3/chapter18Thumbnail.jpg', 805, 6, 3, NULL, '아이섀도 기초', NULL, 'lectures/6/chapters/3/chapter03.mp4'),
  (19, NOW() - INTERVAL 36 DAY, NOW() - INTERVAL 36 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/6/chapters/4/chapter19Thumbnail.jpg', 217, 6, 4, NULL, '아이라이너 그리기', NULL, 'lectures/6/chapters/4/chapter04.mp4'),
  (20, NOW() - INTERVAL 36 DAY, NOW() - INTERVAL 36 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/6/chapters/5/chapter20Thumbnail.jpg', 199, 6, 5, NULL, '립 메이크업', NULL, 'lectures/6/chapters/5/chapter05.mp4'),
  (21, NOW() - INTERVAL 36 DAY, NOW() - INTERVAL 36 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/6/chapters/6/chapter21Thumbnail.jpg', 278, 6, 6, NULL, '데일리 풀 메이크업', NULL, 'lectures/6/chapters/6/chapter06.mp4'),
  (22, NOW() - INTERVAL 32 DAY, NOW() - INTERVAL 32 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/7/chapters/1/chapter22Thumbnail.jpg', 1445, 7, 1, NULL, '수채화 도구 소개', NULL, 'lectures/7/chapters/1/chapter01.mp4'),
  (23, NOW() - INTERVAL 32 DAY, NOW() - INTERVAL 32 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/7/chapters/2/chapter23Thumbnail.jpg', 200, 7, 2, NULL, '기본 붓터치 연습', NULL, 'lectures/7/chapters/2/chapter02.mp4'),
  (24, NOW() - INTERVAL 32 DAY, NOW() - INTERVAL 32 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/7/chapters/3/chapter24Thumbnail.jpg', 805, 7, 3, NULL, '번짐 기법', NULL, 'lectures/7/chapters/3/chapter03.mp4'),
  (25, NOW() - INTERVAL 32 DAY, NOW() - INTERVAL 32 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/7/chapters/4/chapter25Thumbnail.jpg', 217, 7, 4, NULL, '색 혼합과 그라데이션', NULL, 'lectures/7/chapters/4/chapter04.mp4'),
  (26, NOW() - INTERVAL 32 DAY, NOW() - INTERVAL 32 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/7/chapters/5/chapter26Thumbnail.jpg', 199, 7, 5, NULL, '풍경 스케치', NULL, 'lectures/7/chapters/5/chapter05.mp4'),
  (27, NOW() - INTERVAL 32 DAY, NOW() - INTERVAL 32 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/7/chapters/6/chapter27Thumbnail.jpg', 278, 7, 6, NULL, '꽃 수채화', NULL, 'lectures/7/chapters/6/chapter06.mp4'),
  (28, NOW() - INTERVAL 32 DAY, NOW() - INTERVAL 32 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/7/chapters/7/chapter28Thumbnail.jpg', 596, 7, 7, NULL, '동물 수채화', NULL, 'lectures/7/chapters/7/chapter07.mp4'),
  (29, NOW() - INTERVAL 32 DAY, NOW() - INTERVAL 32 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/7/chapters/8/chapter29Thumbnail.png', 1017, 7, 8, NULL, '나만의 작품 완성', NULL, 'lectures/7/chapters/8/chapter08.mp4'),
  (30, NOW() - INTERVAL 28 DAY, NOW() - INTERVAL 28 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/8/chapters/1/chapter30Thumbnail.jpg', 1445, 8, 1, NULL, '드로잉 도구와 기초선', NULL, 'lectures/8/chapters/1/chapter01.mp4'),
  (31, NOW() - INTERVAL 28 DAY, NOW() - INTERVAL 28 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/8/chapters/2/chapter31Thumbnail.jpg', 200, 8, 2, NULL, '도형으로 형태 잡기', NULL, 'lectures/8/chapters/2/chapter02.mp4'),
  (32, NOW() - INTERVAL 28 DAY, NOW() - INTERVAL 28 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/8/chapters/3/chapter32Thumbnail.jpg', 805, 8, 3, NULL, '명암 표현 기초', NULL, 'lectures/8/chapters/3/chapter03.mp4'),
  (33, NOW() - INTERVAL 28 DAY, NOW() - INTERVAL 28 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/8/chapters/4/chapter33Thumbnail.jpg', 217, 8, 4, NULL, '정물 드로잉', NULL, 'lectures/8/chapters/4/chapter04.mp4'),
  (34, NOW() - INTERVAL 28 DAY, NOW() - INTERVAL 28 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/8/chapters/5/chapter34Thumbnail.jpg', 199, 8, 5, NULL, '얼굴 비율과 구조', NULL, 'lectures/8/chapters/5/chapter05.mp4'),
  (35, NOW() - INTERVAL 28 DAY, NOW() - INTERVAL 28 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/8/chapters/6/chapter35Thumbnail.jpg', 278, 8, 6, NULL, '눈코입 디테일', NULL, 'lectures/8/chapters/6/chapter06.mp4'),
  (36, NOW() - INTERVAL 28 DAY, NOW() - INTERVAL 28 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/8/chapters/7/chapter36Thumbnail.jpg', 596, 8, 7, NULL, '손 드로잉', NULL, 'lectures/8/chapters/7/chapter07.mp4'),
  (37, NOW() - INTERVAL 28 DAY, NOW() - INTERVAL 28 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/8/chapters/8/chapter37Thumbnail.jpg', 1017, 8, 8, NULL, '전신 인체 비율', NULL, 'lectures/8/chapters/8/chapter08.mp4'),
  (38, NOW() - INTERVAL 28 DAY, NOW() - INTERVAL 28 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/8/chapters/9/chapter38Thumbnail.jpg', 1312, 8, 9, NULL, '포즈와 동세 표현', NULL, 'lectures/8/chapters/9/chapter09.mp4'),
  (39, NOW() - INTERVAL 28 DAY, NOW() - INTERVAL 28 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/8/chapters/10/chapter39Thumbnail.jpg', 609, 8, 10, NULL, '캐릭터 완성 드로잉', NULL, 'lectures/8/chapters/10/chapter10.mp4'),
  (40, NOW() - INTERVAL 24 DAY, NOW() - INTERVAL 24 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/9/chapters/1/chapter40Thumbnail.jpg', 1445, 9, 1, NULL, '베이킹 도구와 재료', NULL, 'lectures/9/chapters/1/chapter01.mp4'),
  (41, NOW() - INTERVAL 24 DAY, NOW() - INTERVAL 24 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/9/chapters/2/chapter41Thumbnail.jpg', 200, 9, 2, NULL, '쿠키 만들기', NULL, 'lectures/9/chapters/2/chapter02.mp4'),
  (42, NOW() - INTERVAL 24 DAY, NOW() - INTERVAL 24 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/9/chapters/3/chapter42Thumbnail.jpg', 805, 9, 3, NULL, '머핀 만들기', NULL, 'lectures/9/chapters/3/chapter03.mp4'),
  (43, NOW() - INTERVAL 24 DAY, NOW() - INTERVAL 24 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/9/chapters/4/chapter43Thumbnail.jpg', 217, 9, 4, NULL, '케이크 시트 만들기', NULL, 'lectures/9/chapters/4/chapter04.mp4'),
  (44, NOW() - INTERVAL 20 DAY, NOW() - INTERVAL 20 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/10/chapters/1/chapter44Thumbnail.jpg', 1445, 10, 1, NULL, '인사와 자기소개', NULL, 'lectures/10/chapters/1/chapter01.mp4'),
  (45, NOW() - INTERVAL 20 DAY, NOW() - INTERVAL 20 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/10/chapters/2/chapter45Thumbnail.jpg', 200, 10, 2, NULL, '숫자와 날짜 표현', NULL, 'lectures/10/chapters/2/chapter02.mp4'),
  (46, NOW() - INTERVAL 20 DAY, NOW() - INTERVAL 20 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/10/chapters/3/chapter46Thumbnail.jpg', 805, 10, 3, NULL, '쇼핑 회화', NULL, 'lectures/10/chapters/3/chapter03.mp4'),
  (47, NOW() - INTERVAL 20 DAY, NOW() - INTERVAL 20 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/10/chapters/4/chapter47Thumbnail.jpg', 217, 10, 4, NULL, '식당 회화', NULL, 'lectures/10/chapters/4/chapter04.mp4'),
  (48, NOW() - INTERVAL 20 DAY, NOW() - INTERVAL 20 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/10/chapters/5/chapter48Thumbnail.jpg', 199, 10, 5, NULL, '길 찾기 회화', NULL, 'lectures/10/chapters/5/chapter05.mp4'),
  (49, NOW() - INTERVAL 20 DAY, NOW() - INTERVAL 20 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/10/chapters/6/chapter49Thumbnail.png', 278, 10, 6, NULL, '병원 회화', NULL, 'lectures/10/chapters/6/chapter06.mp4'),
  (50, NOW() - INTERVAL 20 DAY, NOW() - INTERVAL 20 DAY, NULL, 'https://momocity-bucket.s3.ap-northeast-2.amazonaws.com/lectures/10/chapters/7/chapter50Thumbnail.jpg', 596, 10, 7, NULL, '비즈니스 이메일 영어', NULL, 'lectures/10/chapters/7/chapter07.mp4');
-- =====================================================================
--  4. enrollment — 학생30 × lecture3
-- =====================================================================
INSERT INTO `enrollment` (`id`, `completed_count`, `enrolled_at`, `lecture_id`, `total_progress`, `user_id`, `is_completed`) VALUES
  (1, 0, NOW() - INTERVAL 118 DAY, 1, 0, 12, FALSE),
  (2, 0, NOW() - INTERVAL 118 DAY, 2, 0, 12, FALSE),
  (3, 0, NOW() - INTERVAL 118 DAY, 3, 0, 12, FALSE),
  (4, 0, NOW() - INTERVAL 117 DAY, 1, 0, 13, FALSE),
  (5, 0, NOW() - INTERVAL 117 DAY, 2, 0, 13, FALSE),
  (6, 0, NOW() - INTERVAL 117 DAY, 3, 0, 13, FALSE),
  (7, 0, NOW() - INTERVAL 116 DAY, 1, 0, 14, FALSE),
  (8, 0, NOW() - INTERVAL 116 DAY, 2, 0, 14, FALSE),
  (9, 0, NOW() - INTERVAL 116 DAY, 3, 0, 14, FALSE),
  (10, 0, NOW() - INTERVAL 115 DAY, 1, 0, 15, FALSE),
  (11, 0, NOW() - INTERVAL 115 DAY, 2, 0, 15, FALSE),
  (12, 0, NOW() - INTERVAL 115 DAY, 3, 0, 15, FALSE),
  (13, 0, NOW() - INTERVAL 114 DAY, 1, 0, 16, FALSE),
  (14, 0, NOW() - INTERVAL 114 DAY, 2, 0, 16, FALSE),
  (15, 0, NOW() - INTERVAL 114 DAY, 3, 0, 16, FALSE),
  (16, 0, NOW() - INTERVAL 113 DAY, 1, 0, 17, FALSE),
  (17, 0, NOW() - INTERVAL 113 DAY, 2, 0, 17, FALSE),
  (18, 0, NOW() - INTERVAL 113 DAY, 3, 0, 17, FALSE),
  (19, 0, NOW() - INTERVAL 112 DAY, 1, 0, 18, FALSE),
  (20, 0, NOW() - INTERVAL 112 DAY, 2, 0, 18, FALSE),
  (21, 0, NOW() - INTERVAL 112 DAY, 3, 0, 18, FALSE),
  (22, 0, NOW() - INTERVAL 111 DAY, 1, 0, 19, FALSE),
  (23, 0, NOW() - INTERVAL 111 DAY, 2, 0, 19, FALSE),
  (24, 0, NOW() - INTERVAL 111 DAY, 3, 0, 19, FALSE),
  (25, 0, NOW() - INTERVAL 110 DAY, 1, 0, 20, FALSE),
  (26, 0, NOW() - INTERVAL 110 DAY, 2, 0, 20, FALSE),
  (27, 0, NOW() - INTERVAL 110 DAY, 3, 0, 20, FALSE),
  (28, 0, NOW() - INTERVAL 109 DAY, 1, 0, 21, FALSE),
  (29, 0, NOW() - INTERVAL 109 DAY, 2, 0, 21, FALSE),
  (30, 0, NOW() - INTERVAL 109 DAY, 3, 0, 21, FALSE),
  (31, 0, NOW() - INTERVAL 108 DAY, 1, 0, 22, FALSE),
  (32, 0, NOW() - INTERVAL 108 DAY, 2, 0, 22, FALSE),
  (33, 0, NOW() - INTERVAL 108 DAY, 3, 0, 22, FALSE),
  (34, 0, NOW() - INTERVAL 107 DAY, 1, 0, 23, FALSE),
  (35, 0, NOW() - INTERVAL 107 DAY, 2, 0, 23, FALSE),
  (36, 0, NOW() - INTERVAL 107 DAY, 3, 0, 23, FALSE),
  (37, 0, NOW() - INTERVAL 106 DAY, 1, 0, 24, FALSE),
  (38, 0, NOW() - INTERVAL 106 DAY, 2, 0, 24, FALSE),
  (39, 0, NOW() - INTERVAL 106 DAY, 3, 0, 24, FALSE),
  (40, 0, NOW() - INTERVAL 105 DAY, 1, 0, 25, FALSE),
  (41, 0, NOW() - INTERVAL 105 DAY, 2, 0, 25, FALSE),
  (42, 0, NOW() - INTERVAL 105 DAY, 3, 0, 25, FALSE),
  (43, 0, NOW() - INTERVAL 104 DAY, 1, 0, 26, FALSE),
  (44, 0, NOW() - INTERVAL 104 DAY, 2, 0, 26, FALSE),
  (45, 0, NOW() - INTERVAL 104 DAY, 3, 0, 26, FALSE),
  (46, 0, NOW() - INTERVAL 103 DAY, 1, 0, 27, FALSE),
  (47, 0, NOW() - INTERVAL 103 DAY, 2, 0, 27, FALSE),
  (48, 0, NOW() - INTERVAL 103 DAY, 3, 0, 27, FALSE),
  (49, 0, NOW() - INTERVAL 102 DAY, 1, 0, 28, FALSE),
  (50, 0, NOW() - INTERVAL 102 DAY, 2, 0, 28, FALSE),
  (51, 0, NOW() - INTERVAL 102 DAY, 3, 0, 28, FALSE),
  (52, 0, NOW() - INTERVAL 101 DAY, 1, 0, 29, FALSE),
  (53, 0, NOW() - INTERVAL 101 DAY, 2, 0, 29, FALSE),
  (54, 0, NOW() - INTERVAL 101 DAY, 3, 0, 29, FALSE),
  (55, 0, NOW() - INTERVAL 100 DAY, 1, 0, 30, FALSE),
  (56, 0, NOW() - INTERVAL 100 DAY, 2, 0, 30, FALSE),
  (57, 0, NOW() - INTERVAL 100 DAY, 3, 0, 30);
-- =====================================================================
--  5. friend — small
-- =====================================================================
INSERT INTO `friend` (`id`, `created_at`, `status`, `updated_at`, `from_user_id`, `to_user_id`) VALUES
  (1, NOW() - INTERVAL 40 DAY, 'FRIEND', NOW() - INTERVAL 40 DAY, 12, 13),
  (2, NOW() - INTERVAL 35 DAY, 'FRIEND', NOW() - INTERVAL 35 DAY, 13, 12),
  (3, NOW() - INTERVAL 30 DAY, 'FRIEND', NOW() - INTERVAL 30 DAY, 12, 14),
  (4, NOW() - INTERVAL 25 DAY, 'SENT', NOW() - INTERVAL 25 DAY, 15, 12),
  (5, NOW() - INTERVAL 20 DAY, 'BLOCK', NOW() - INTERVAL 20 DAY, 12, 27);

SET FOREIGN_KEY_CHECKS = 1;
